- name: install apache at the latest version
  become: yes
  yum:
    name: httpd
    state: latest
  
- name: start apache 
  become: yes
  service:
    name: httpd
    state: started
    enabled: yes

- name: open http firewall port
  become: yes
  firewalld:
    service: http 
    zone: public
    immediate: yes # this is the firewall-cmd --reload
    permanent: true
    state: enabled
    