---
- hosts: web_servers    
  roles:
    - apache    
    - php
    - git
    - setup
    
- hosts: db_servers 
  roles:
    - postgres    

- hosts: admin_servers 
  roles:
    - pgadmin   
    
  

  
  