---

- name: Start and enable service 
  become: yes
  service:
    name: "{{ service }}" 
    state: started
    enabled: yes


- name: Configure SELinux to allow httpd to connect to remote database
  become: yes
  seboolean:
    name: httpd_can_network_connect_db
    state: true
    persistent: yes
  

    
- name: Clone a repo with separate git directory
  git:
    repo: "{{ git_repo }}"  
    dest: /home/ansible/{{ git_folder }}


- name: Open firewall port for service
  become: yes
  firewalld:
    service: "{{ firewall_service }}" 
    zone: public
    immediate: yes # this is the firewall-cmd --reload
    permanent: true
    state: enabled

- name: Copy files between directories on remote servers
  become: yes
  copy:
    src: "{{ src_path }}"
    dest: "{{ dest_path }}"
    remote_src: yes 
    
