---
#install packages

package: 
  - "*"
  #- httpd
  - git
  - epel-release


#install repo-rpms

repo_rpm: https://download.postgresql.org/pub/repos/yum/reporpms/EL-7-x86_64/pgdg-redhat-repo-latest.noarch.rpm

#enablerepo

repo_name: pgdg12
  

#install packages from repo

repo_package: 
  - postgresql12-server
  - postgresql12-contrib
  - python3-psycopg2

#start and enable service 

service: postgresql-12

#Clone a repo

#git_repo: https://github.com/nick1846/docker.git

#git destination path

#git_folder: 

#open firewall port for service

##firewall_service: 

#copy files from [src_path] to [dest_path] on remote servers

#src_path: 

#dest_path: 


  




