---
#install packages

package: 
  - "*"
  - httpd
  - git
  - epel-release.noarch
  - libsemanage-python
  

#install repo-rpms

repo_rpm: "http://rpms.remirepo.net/enterprise/remi-release-7.rpm"

#enablerepo

repo_name:
  - remi
  - remi-php74

#install packages from repo

repo_package:
  - php-cli 
  - php-common
  - php-fpm
  - php-json
  - php-opcache
  - php-pdo
  - php-pgsql

#start and enable service 

service: httpd

#Clone a repo

git_repo: https://github.com/nick1846/docker.git

#git destination path

git_folder: web-project

#open firewall port for service

firewall_service: http

#copy files from [src_path] to [dest_path] on remote servers

src_path: /home/ansible/web-project/docker-compose/web/

dest_path: /var/www/html/


  




