- name: install  git
  become: yes
  yum: 
    name: git
    state: latest

- name: Clone a repo with separate git directory
  git:
    repo: https://github.com/nick1846/docker.git
    dest: /home/ansible/web-project