---

- name: Install packages
  become: true
  yum:
    name: "{{ package }}"
    state: present


- name: Install repo rpm 
  become: true
  yum:
    name: 
      - "{{ repo_rpm }}" 
    state: present


- name: Install from repo rpm
  become: true
  yum: 
    enablerepo: "{{ repo_name }}" 
    name: "{{ repo_package }}" 
    state: present
  


      

    

